# Generated by Django 2.2.5 on 2020-09-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('body', models.TextField()),
                ('date_time', models.DateField(auto_now_add=True)),
                ('author', models.CharField(max_length=200)),
            ],
        ),
    ]
